/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrezUIBreadcrumb: typeof import('./components/PrezUIBreadcrumb.vue')['default']
    PrezUIDataConcept: typeof import('./components/PrezUIDataConcept.vue')['default']
    PrezUIDataConceptScheme: typeof import('./components/PrezUIDataConceptScheme.vue')['default']
    PrezUIDataPage: typeof import('./components/PrezUIDataPage.vue')['default']
    PrezUIDataProvider: typeof import('./components/PrezUIDataProvider.vue')['default']
    PrezUIHeader: typeof import('./components/PrezUIHeader.vue')['default']
    PrezUIItemList: typeof import('./components/PrezUIItemList.vue')['default']
    PrezUIItemTable: typeof import('./components/PrezUIItemTable.vue')['default']
    PrezUIItemTableProperty: typeof import('./components/PrezUIItemTableProperty.vue')['default']
    PrezUILink: typeof import('./components/PrezUILink.vue')['default']
    PrezUILiteral: typeof import('./components/PrezUILiteral.vue')['default']
    PrezUILoading: typeof import('./components/PrezUILoading.vue')['default']
    PrezUIMessage: typeof import('./components/PrezUIMessage.vue')['default']
    PrezUINode: typeof import('./components/PrezUINode.vue')['default']
    PrezUIPageFooter: typeof import('./components/PrezUIPageFooter.vue')['default']
    PrezUIPageHeader: typeof import('./components/PrezUIPageHeader.vue')['default']
    PrezUIPageLayout: typeof import('./components/PrezUIPageLayout.vue')['default']
    PrezUIPageMenu: typeof import('./components/PrezUIPageMenu.vue')['default']
    PrezUIPagination: typeof import('./components/PrezUIPagination.vue')['default']
    PrezUIProfiles: typeof import('./components/PrezUIProfiles.vue')['default']
    PrezUIStaticPage: typeof import('./components/PrezUIStaticPage.vue')['default']
    PrezUITerm: typeof import('./components/PrezUITerm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tester: typeof import('./components/Tester.vue')['default']
  }
}
