# https://taskfile.dev

version: '3'

tasks:
  install:
    cmd: pnpm install
  
  run:lib:
    dir: packages/prez-lib
    cmd: pnpm dev
  
  build:lib:
    dir: packages/prez-lib
    cmd: pnpm build
  
  run:components:
    dir: packages/prez-components
    cmd: pnpm dev
  
  build:components:
    dir: packages/prez-components
    cmd: pnpm build
  
  build:
    cmds:
      - task: build:lib
      - task: build:components
  
  run:ui:
    dir: packages/prez-ui
    cmd: pnpm dev
  
  generate:
    dir: packages/prez-ui
    cmd: pnpm generate
  
  run:generate:
    dir: packages/prez-ui
    cmd: npx serve .output/public
  
  run:
    cmds:
      - task: install
      - task: build
      - task: run:ui
  
  type:lib:
    dir: packages/prez-lib
    cmd: pnpm types
  
  type:components:
    dir: packages/prez-components
    cmd: pnpm types
  
  type:ui:
    dir: packages/prez-ui
    cmd: pnpm types
  
  type:template:
    dir: packages/create-prez-app/template
    cmd: pnpm types
  
  type:
    cmds:
      - task: type:lib
      - task: type:components
      - task: type:ui
      - task: type:template
