/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CompA: typeof import('./components/compA.vue')['default']
    copy: typeof import('./components/themes/primevue/PrezUILiteral copy.vue')['default']
    PrezDataProvider: typeof import('./components/PrezDataProvider.vue')['default']
    PrezDataProviderTerm: typeof import('./components/PrezDataProviderTerm.vue')['default']
    PrezUIDebug: typeof import('./components/PrezUIDebug.vue')['default']
    PrezUIHeader: typeof import('./components/PrezUIHeader.vue')['default']
    PrezUIItem: typeof import('./components/PrezUIItem.vue')['default']
    PrezUILiteral: typeof import('./components/PrezUILiteral.vue')['default']
    PrezUILoading: typeof import('./components/PrezUILoading.vue')['default']
    PrezUIMessage: typeof import('./components/PrezUIMessage.vue')['default']
    PrezUINode: typeof import('./components/PrezUINode.vue')['default']
    PrezUIPropertyTable: typeof import('./components/PrezUIPropertyTable.vue')['default']
    PrezUITableProperties: typeof import('./components/themes/primevue/PrezUITableProperties.vue')['default']
    PrezUITerm: typeof import('./components/PrezUITerm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/sb/Settings.vue')['default']
    WithTheme: typeof import('./components/WithTheme.vue')['default']
  }
}
