/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComponentTree: typeof import('./components/ComponentTree.vue')['default']
    copy: typeof import('./components/PrezUIDataPage copy.vue')['default']
    DebugTree: typeof import('./components/DebugTree.vue')['default']
    Dx: typeof import('./components/dx.vue')['default']
    PrezDataProvider: typeof import('./components/PrezDataProvider.vue')['default']
    PrezDataProviderTerm: typeof import('./components/PrezDataProviderTerm.vue')['default']
    PrezUI: typeof import('./components/PrezUI.vue')['default']
    PrezUIBreadcrumbs: typeof import('./components/PrezUIBreadcrumbs.vue')['default']
    PrezUIConcept: typeof import('./components/PrezUIConcept.vue')['default']
    PrezUIConceptHierarchy: typeof import('./components/PrezUIConceptHierarchy.vue')['default']
    PrezUIData: typeof import('./components/PrezUIData.vue')['default']
    PrezUIDataItem: typeof import('./components/PrezUIDataItem.vue')['default']
    PrezUIDataList: typeof import('./components/PrezUIDataList.vue')['default']
    PrezUIDataPage: typeof import('./components/PrezUIDataPage.vue')['default']
    PrezUIDataProvider: typeof import('./components/PrezUIDataProvider.vue')['default']
    PrezUIDebug: typeof import('./components/PrezUIDebug.vue')['default']
    PrezUIHeader: typeof import('./components/PrezUIHeader.vue')['default']
    PrezUIItem: typeof import('./components/PrezUIItem.vue')['default']
    PrezUIItemList: typeof import('./components/PrezUIItemList.vue')['default']
    PrezUIItemTable: typeof import('./components/PrezUIItemTable.vue')['default']
    PrezUILayouts: typeof import('./components/PrezUILayouts.vue')['default']
    PrezUILayoutStacked: typeof import('./components/PrezUILayoutStacked.vue')['default']
    PrezUILink: typeof import('./components/PrezUILink.vue')['default']
    PrezUIList: typeof import('./components/PrezUIList.vue')['default']
    PrezUILiteral: typeof import('./components/PrezUILiteral.vue')['default']
    PrezUILoading: typeof import('./components/PrezUILoading.vue')['default']
    PrezUIMessage: typeof import('./components/PrezUIMessage.vue')['default']
    PrezUINode: typeof import('./components/PrezUINode.vue')['default']
    PrezUIPageData: typeof import('./components/PrezUIPageData.vue')['default']
    PrezUIPageFooter: typeof import('./components/PrezUIPageFooter.vue')['default']
    PrezUIPageHeader: typeof import('./components/PrezUIPageHeader.vue')['default']
    PrezUIPageLayout: typeof import('./components/PrezUIPageLayout.vue')['default']
    PrezUIPageLayouts: typeof import('./components/PrezUIPageLayouts.vue')['default']
    PrezUIPageMenu: typeof import('./components/PrezUIPageMenu.vue')['default']
    PrezUIPagination: typeof import('./components/PrezUIPagination.vue')['default']
    PrezUIProfiles: typeof import('./components/PrezUIProfiles.vue')['default']
    PrezUIPropertyTable: typeof import('./components/PrezUIPropertyTable.vue')['default']
    PrezUIStaticPage: typeof import('./components/PrezUIStaticPage.vue')['default']
    PrezUITerm: typeof import('./components/PrezUITerm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/sb/Settings.vue')['default']
    TestA: typeof import('./components/testA.vue')['default']
    TestABC: typeof import('./components/testABC.vue')['default']
    Tester: typeof import('./components/Tester.vue')['default']
    WithTheme: typeof import('./components/WithTheme.vue')['default']
  }
}
